### ISSUE TITLE
unixODBC config files

### ISSUE THREAD

**Issue by zeeshanafzal** [lionheart/django-pyodbc#152]
I need to config two following files:
**odbcinst.ini**
**odbc.ini**

![image](https://user-images.githubusercontent.com/2690195/33799115-f7634be2-dd46-11e7-8ba9-9f5491e900df.png)

and my path to FreeTDS is: /usr/local/Cellar/freetds/1.00.79/etc

I am confused that how to change this into the first file. Also I didn't find any libtdsodbc.so in freeTDS lib folder.

Looking for the help.

**Comment by RossRogers** [comment]
Hi zeeshanafzal,

django-pyodbc is built on top of pyodbc, which uses unixODBC.  Per our readme:


>  You may need to configure your machine and drivers to do an ODBC connection to your database server, if you haven't already. For Linux this involves installing and [configuring Unix ODBC and FreeTDS .](http://www.unixodbc.org/doc/FreeTDS.html) Iterate on the command line to test your pyodbc connection like:
> 
>     python -c 'import pyodbc; print(pyodbc.connect("DSN=foobar_mssql_data_source_name;UID=foo;PWD=bar").cursor().execute("select 1"))'
> 

So, per the readme, please go to http://www.unixodbc.org/doc/FreeTDS.html to figure out your odbc connection and then modify the above `python -c ...` command to test it on the command line.

This is not a django-pyodbc issue, so I am closing.  Feel free to comment more in order to receive help, if we can, but this is a unixODBC issue, not a django-pyodbc issue.  

Good luck!
