### ISSUE TITLE
DecimalField and Conversion to Float

### ISSUE THREAD

**Issue by jackson0810** [lionheart/django-pyodbc#31]
Hi,
This is more of a question that may not be an issue.  In my model I have a DecimalField with max_digits = 20, and decimal_places = 2.  However, when I enter 444444444444444444 I notice the number is being saved as 444444444444444416.  When I looked at the following code (operations.py):

```
def value_to_db_decimal(self, value, max_digits, decimal_places):
        """
        Transform a decimal.Decimal value to an object compatible with what is
        expected by the backend driver for decimal (numeric) columns.
        """
        if value is None:
            return None
        if isinstance(value, decimal.Decimal):
            context = decimal.getcontext().copy()
            context.prec = max_digits
            return "%.*f" % (decimal_places, value.quantize(decimal.Decimal(".1") ** decimal_places, context=context))
        else:
            return "%.*f" % (decimal_places, value)
```

I notice that the decimal data is being converted to a floating point.  Would you be able to add some clarification as to why this is needed?  I am in no way saying it is wrong.  I am just trying to understand it.

Thanks,
Derrick

**Comment by RossRogers** [comment]
So... no time machine here, but the reason why it ends in 16 instead of 44 is because 444444444444444444 has 59 bits of precision needed to store the number:
   
    >>> from math import log
    >>> log(444444444444444444)/log(2)
    58.62478070653021

Since a python 64-bit double can only store 52 bits of "significance". The extra bits are then rounded off according to IEEE 754 specification.  [More details on wikipedia.](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)
